version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: apigateway-db
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
    volumes:
      - ./_docker-data/postgres:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - apigateway
    env_file:
      - .env
  api-gateway:
    container_name: api-gateway
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - service-user
      - service-employee
    networks:
      - apigateway
    expose:
      - "3000"
    env_file:
      - .env
  service-user:
    container_name: service-user
    build: 
      context: ./service-user
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - postgres
    networks:
      - apigateway
    env_file:
      - .env
    expose:
      - "3001"
  service-employee:
    container_name: service-employee
    build: 
      context: ./service-employee
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    depends_on:
      - postgres
      - service-user
    networks:
      - apigateway
    env_file:
      - .env
    expose:
      - "3002"

networks:
  apigateway:
    driver: bridge
