version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: apigateway-db
    environment:
      - POSTGRES_USER=habi
      - POSTGRES_PASSWORD=habi123
      - POSTGRES_DB=apigateway
    ports:
      - 5432:5432
    volumes:
      - ./_docker-data/postgres:/var/lib/postgresql/data
    restart: on-failure
