version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: apigateway-db-dev
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - 5432:5432
    volumes:
      - ./_docker-data/postgres-dev:/var/lib/postgresql/data
    restart: on-failure
    networks:
      - apigateway
    env_file:
      - .env.dev